Repository ls1intum/prompt2, pull requests merged in 2025-03, with the labels that each got.

#229 Bump jinja to 3.1.6
  docs/requirements.txt
Labels: security fix

#251 DevOps Challenge: Register Component
  servers/core/coursePhaseType/initializeTypes.go
  servers/core/coursePhaseType/main.go
  servers/core/db/query/course_phase_type.sql
  servers/core/db/sqlc/course_phase_type.sql.go
Labels: Component:: GitHubCodingChallenge

#254 253 move readme on how to add new component into documentation
  docs/contributor/new_component.md
  docs/index.md
Labels: documentation

#250 Application Phase Auto Accept
  clients/core/src/managementConsole/applicationAdministration/hooks/useParseApplicationMetaData.ts
  clients/core/src/managementConsole/applicationAdministration/interfaces/applicationMetaData.ts
  clients/core/src/managementConsole/applicationAdministration/pages/ApplicationConfiguration/components/ApplicationConfigDialog.tsx
  servers/core/applicationAdministration/service.go
  servers/core/db/query/application.sql
  servers/core/db/sqlc/application.sql.go
Labels: Component: Application, Component:: GitHubCodingChallenge

#249 `Intro Course` Tutor Import via Keycloak
  clients/core/src/managementConsole/applicationAdministration/components/ApplicationDataWrapper.tsx
  clients/intro_course_developer_component/routes/index.tsx
  clients/intro_course_developer_component/sidebar/index.tsx
  clients/intro_course_developer_component/src/introCourse/interfaces/CreateKeycloakGroup.ts
  clients/intro_course_developer_component/src/introCourse/interfaces/Tutor.ts
  clients/intro_course_developer_component/src/introCourse/network/mutations/createCustomKeycloakGroup.ts
  clients/intro_course_developer_component/src/introCourse/network/mutations/importTutors.ts
  clients/intro_course_developer_component/src/introCourse/network/queries/getAllTutors.ts
  clients/intro_course_developer_component/src/introCourse/network/queries/getStudentsOfCoursePhase.ts
  clients/intro_course_developer_component/src/introCourse/pages/TutorImport/TutorImportPage.tsx
  clients/intro_course_developer_component/src/introCourse/pages/TutorImport/components/KeycloakGroupCreation.tsx
  clients/intro_course_developer_component/src/introCourse/pages/TutorImport/components/StudentSelection.tsx
  clients/intro_course_developer_component/src/introCourse/pages/TutorImport/components/TutorImportDialog.tsx
  clients/intro_course_developer_component/src/introCourse/pages/TutorImport/components/TutorTable.tsx
  clients/shared_library/hooks/useGetCoursePhase.ts
  servers/core/coursePhase/coursePhaseParticipation/router.go
  servers/core/coursePhase/coursePhaseParticipation/service.go
  servers/core/db/query/course_phase_participation.sql
  servers/core/db/sqlc/course_phase_participation.sql.go
  servers/core/keycloakRealmManager/router.go
  servers/core/keycloakRealmManager/service.go
  servers/core/student/studentDTO/get_student.go
  servers/intro_course/coreRequests/addTutorToKeycloakGroup.go
  servers/intro_course/coreRequests/coreRequestDTOs/addStudentsToGroup.go
  servers/intro_course/coreRequests/sendCoreRequest.go
  servers/intro_course/db/migration/0001_schema.up.sql
  servers/intro_course/db/query/tutor.sql
  servers/intro_course/db/sqlc/models.go
  servers/intro_course/db/sqlc/tutor.sql.go
  servers/intro_course/keycloakTokenVerifier/getIsStudent.go
  servers/intro_course/keycloakTokenVerifier/getLecturerAndEditorRole.go
  servers/intro_course/keycloakTokenVerifier/keycloakCoreRequests/coursePhaseRoleMapping.go
  servers/intro_course/keycloakTokenVerifier/keycloakCoreRequests/isStudent.go
  servers/intro_course/keycloakTokenVerifier/keycloakCoreRequests/sendCoreRequest.go
  servers/intro_course/main.go
  servers/intro_course/tutor/main.go
  servers/intro_course/tutor/router.go
  servers/intro_course/tutor/service.go
  servers/intro_course/tutor/tutorDTO/tutor.go
Labels: Component: IntroCourse

#252 `DevOps challenge` Initialize new component
  .github/workflows/build-and-push-clients.yml
  .github/workflows/deploy-docker.yml
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  clients/core/src/managementConsole/PhaseMapping/ExternalRoutes/DevOpsChallengeRoutes.tsx
  clients/core/src/managementConsole/PhaseMapping/ExternalSidebars/DevOpsChallengeSidebar.tsx
  clients/core/src/managementConsole/PhaseMapping/PhaseRouterMapping.tsx
  clients/core/src/managementConsole/PhaseMapping/PhaseSidebarMapping.tsx
  clients/core/webpack.config.ts
  clients/devops_challenge_component/.yarnrc.yml
  clients/devops_challenge_component/Dockerfile
  clients/devops_challenge_component/eslint.config.mjs
  clients/devops_challenge_component/package.json
  clients/devops_challenge_component/public/prompt_logo.svg
  clients/devops_challenge_component/public/template.html
  clients/devops_challenge_component/readme
  clients/devops_challenge_component/routes/index.tsx
  clients/devops_challenge_component/sidebar/index.tsx
  clients/devops_challenge_component/src/App.tsx
  clients/devops_challenge_component/src/bootstrap.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/GitHub/GitHubPage.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/Overview/OverviewPage.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/SettingsPage/SettingsPage.tsx
  clients/devops_challenge_component/src/index.js
  clients/devops_challenge_component/tailwind.config.js
  clients/devops_challenge_component/tsconfig.json
  clients/devops_challenge_component/webpack.config.ts
  clients/eslint.config.mjs
  clients/lerna.json
  clients/package.json
  clients/yarn.lock
  docker-compose.prod.yml
  servers/core/coursePhaseType/initializeTypes.go
  servers/core/coursePhaseType/main.go
  servers/core/db/query/course_phase_type.sql
  servers/core/db/sqlc/course_phase_type.sql.go
Labels: New Phase, Component:: GitHubCodingChallenge

#255 `Assessment` Initialize new component
  .github/workflows/build-and-push-clients.yml
  .github/workflows/deploy-docker.yml
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  clients/assessment_component/.yarnrc.yml
  clients/assessment_component/Dockerfile
  clients/assessment_component/eslint.config.mjs
  clients/assessment_component/package.json
  clients/assessment_component/public/prompt_logo.svg
  clients/assessment_component/public/template.html
  clients/assessment_component/readme
  clients/assessment_component/routes/index.tsx
  clients/assessment_component/sidebar/index.tsx
  clients/assessment_component/src/App.tsx
  clients/assessment_component/src/assessment/Overview/OverviewPage.tsx
  clients/assessment_component/src/assessment/Settings/SettingsPage.tsx
  clients/assessment_component/src/bootstrap.tsx
  clients/assessment_component/src/index.js
  clients/assessment_component/tailwind.config.js
  clients/assessment_component/tsconfig.json
  clients/assessment_component/webpack.config.ts
  clients/core/src/managementConsole/PhaseMapping/ExternalRoutes/AssessmentRoutes.tsx
  clients/core/src/managementConsole/PhaseMapping/ExternalSidebars/AssessmentSidebar.tsx
  clients/core/src/managementConsole/PhaseMapping/PhaseRouterMapping.tsx
  clients/core/src/managementConsole/PhaseMapping/PhaseSidebarMapping.tsx
  clients/core/webpack.config.ts
  clients/eslint.config.mjs
  clients/lerna.json
  clients/package.json
  clients/yarn.lock
  docker-compose.prod.yml
Labels: New Phase, Component:: Assessment

#310 `General`: add linting via strategy matrix
  .github/workflows/dev.yml
  .github/workflows/lint-clients.yml
  .github/workflows/lint-servers.yml
  clients/core/eslint.config.mjs
Labels: GitHub Action

#291 `DevOps Challenge`: Trigger challenge assessment
  .github/workflows/deploy-docker.yml
  clients/core/public/env.js
  clients/core/public/env.template.js
  clients/devops_challenge_component/routes/index.tsx
  clients/devops_challenge_component/sidebar/index.tsx
  clients/devops_challenge_component/src/devops_challenge/DevOpsChallengeDataShell.tsx
  clients/devops_challenge_component/src/devops_challenge/DevOpsChallengePage.tsx
  clients/devops_challenge_component/src/devops_challenge/components/AssessmentPanel.tsx
  clients/devops_challenge_component/src/devops_challenge/components/GithubUsernameInput.tsx
  clients/devops_challenge_component/src/devops_challenge/interfaces/DeveloperProfile.ts
  clients/devops_challenge_component/src/devops_challenge/network/devOpsChallengeServerConfig.ts
  clients/devops_challenge_component/src/devops_challenge/network/mutations/createRepository.ts
  clients/devops_challenge_component/src/devops_challenge/network/mutations/triggerAssessment.ts
  clients/devops_challenge_component/src/devops_challenge/network/queries/getDeveloperProfile.ts
  clients/devops_challenge_component/src/devops_challenge/pages/GitHub/GitHubPage.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/Overview/OverviewPage.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/hooks/useCreateRepository.ts
  clients/devops_challenge_component/src/devops_challenge/pages/hooks/useGetDeveloperProfile.ts
  clients/devops_challenge_component/src/devops_challenge/pages/hooks/useTriggerAssessment.ts
  clients/devops_challenge_component/src/devops_challenge/zustand/useDevOpsChallengeStore.tsx
  clients/shared_library/env.ts
Labels: Component:: GitHubCodingChallenge

#314 `DevOps Challenge`: Fix Deployment
  clients/core/public/env.js
  clients/core/public/env.template.js
  clients/devops_challenge_component/src/devops_challenge/network/devOpsChallengeServerConfig.ts
  clients/shared_library/env.ts
  docker-compose.prod.yml
Labels: bug, Component:: GitHubCodingChallenge

#293 `DevOps Challenge`: show overview of challenge results
  clients/devops_challenge_component/routes/index.tsx
  clients/devops_challenge_component/sidebar/index.tsx
  clients/devops_challenge_component/src/devops_challenge/interfaces/DeveloperWithInfo.ts
  clients/devops_challenge_component/src/devops_challenge/network/queries/getAllDeveloperProfiles.ts
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/ResultsOverviewPage.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/columns.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/components/FilterMenu.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/components/GroupActionsMenu.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/hooks/useGetParticipationsWithProfiles.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/interfaces/challengeStatus.ts
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/interfaces/devProfileFilter.ts
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/utils/getChallengeStatusBadge.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/SettingsPage/SettingsPage.tsx
Labels: Component:: GitHubCodingChallenge

#317 `DevOps Challenge`: Improve Developer Profile & Assessment UI Flow
  clients/devops_challenge_component/src/devops_challenge/DevOpsChallengeDataShell.tsx
  clients/devops_challenge_component/src/devops_challenge/DevOpsChallengePage.tsx
  clients/devops_challenge_component/src/devops_challenge/components/Assessment.tsx
  clients/devops_challenge_component/src/devops_challenge/components/AssessmentPanel.tsx
  clients/devops_challenge_component/src/devops_challenge/components/GithubUsernameInput.tsx
  clients/devops_challenge_component/src/devops_challenge/components/RepositoryInformation.tsx
  clients/devops_challenge_component/src/devops_challenge/interfaces/DeveloperProfile.ts
  clients/devops_challenge_component/src/devops_challenge/network/queries/getDeveloperProfile.ts
  clients/devops_challenge_component/src/devops_challenge/pages/hooks/useGetDeveloperProfile.ts
  clients/devops_challenge_component/src/devops_challenge/pages/hooks/useTriggerAssessment.ts
Labels: enhancement, Component:: GitHubCodingChallenge

#337 `General`: Add release_tag input to build workflows in prod.yml
  .github/workflows/build-and-push-clients.yml
  .github/workflows/build-and-push-servers.yml
  .github/workflows/prod.yml
Labels: bug
