Repository ls1intum/prompt2, pull requests merged in 2025-08, with the labels that each got.

#776 Bump version to 2.4.9
  clients/assessment_component/package.json
  clients/core/package.json
  clients/devops_challenge_component/package.json
  clients/interview_component/package.json
  clients/intro_course_developer_component/package.json
  clients/matching_component/package.json
  clients/package.json
  clients/self_team_allocation_component/package.json
  clients/team_allocation_component/package.json
  clients/template_component/package.json
Labels: schau mi o

#775 `Assessment`: Add debounce to assessment form
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletion/components/ActionItemPanel.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentForm/AssessmentForm.tsx
  clients/assessment_component/src/assessment/pages/SelfAndPeerEvaluationPage/components/EvaluationCompletionPage/components/FeedbackItemPanel.tsx
  clients/assessment_component/src/assessment/pages/components/ItemRow.tsx
Labels: schau mi o

#744 `Templating`: Add Course Settings Page and enable lecturers to mark a course as Template
  clients/core/src/App.tsx
  clients/core/src/interfaces/courseTemplateStatus.ts
  clients/core/src/managementConsole/PhaseMapping/ExternalSidebars/CourseSettingsSidebar.tsx
  clients/core/src/managementConsole/applicationAdministration/pages/Mailing/ApplicationMailingSettings.tsx
  clients/core/src/managementConsole/courseSettings/CourseSettingsPage.tsx
  clients/core/src/managementConsole/courseSettings/components/CourseTemplateToggle.tsx
  clients/core/src/managementConsole/courseSettings/hooks/useCourseTemplate.ts
  clients/core/src/managementConsole/layout/Sidebar/InsideSidebar/InsideCourseSidebar.tsx
  clients/core/src/managementConsole/mailingConfig/MailingConfigPage.tsx
  clients/core/src/network/mutations/updateCourseTemplateStatus.ts
  clients/core/src/network/queries/checkCourseTemplateStatus.ts
  clients/shared_library/components/pages/Mailing/CoursePhaseMailing.tsx
  servers/core/course/courseDTO/course_template_status.go
  servers/core/course/courseDTO/get_course.go
  servers/core/course/router.go
  servers/core/course/router_test.go
  servers/core/course/service.go
  servers/core/course/service_test.go
  servers/core/database_dumps/copy_course_test.sql
  servers/core/database_dumps/course_test.sql
  servers/core/db/migration/0014_template.up.sql
  servers/core/db/query/course.sql
  servers/core/db/query/template.sql
  servers/core/db/sqlc/course.sql.go
  servers/core/db/sqlc/models.go
  servers/core/db/sqlc/template.sql.go
  servers/core/go.mod
  servers/core/go.sum
Labels: schau mi o

#729 `Core`: Allow External Mail Server Configurations
  .env.template
  .github/workflows/deploy-docker.yml
  clients/core/public/env.js
  clients/core/src/App.tsx
  clients/yarn.lock
  docker-compose.extern.prod.yml
  docker-compose.prod.yml
  docker-compose.yml
  docs/admin/productionSetup.md
  docs/contributor/setup.md
  servers/assessment/docs/openapi.yaml
  servers/assessment/main.go
  servers/core/applicationAdministration/router_test.go
  servers/core/coursePhaseType/initializeTypes.go
  servers/core/database_dumps/copy_course_test.sql
  servers/core/mailing/main.go
  servers/core/mailing/service.go
  servers/core/main.go
  servers/self_team_allocation/main.go
Labels: schau mi o

#791 `General`: Update Dockerfile to use Distroless Debian 12
  servers/Dockerfile
Labels: dependencies, schau mi o, General

#783 `Assessment`: Update statistics to use grade suggestions
  clients/assessment_component/src/assessment/interfaces/scoreLevelWithParticipation.ts
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletion/AssessmentCompletion.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletion/components/GradeSuggestion.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletion/utils/validateGrade.tsx
  clients/assessment_component/src/assessment/pages/AssessmentParticipantsPage/AssessmentParticipantsPage.tsx
  clients/assessment_component/src/assessment/pages/AssessmentStatisticsPage/AssessmentStatisticsPage.tsx
  clients/assessment_component/src/assessment/pages/AssessmentStatisticsPage/components/FilterBadges.tsx
  clients/assessment_component/src/assessment/pages/AssessmentStatisticsPage/components/FilterMenu.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/SettingsPage.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/AssessmentScoreLevelDiagram.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/AuthorDiagram.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/BarChartWithGrades.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/BarChartWithScoreLevel.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/CategoryDiagram.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/GenderDiagram.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/GradeDistributionDiagram.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/NationalityDiagram.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/ScoreLevelDistributionDiagram.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/gradeDistributionBarChart/GradeDistributionBarChart.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/gradeDistributionBarChart/components/GradeDistributionBar.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/gradeDistributionBarChart/components/GradeDistributionLabel.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/gradeDistributionBarChart/components/GradeDistributionTooltipContent.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/gradeDistributionBarChart/interfaces/GradeDistributionDataPoint.ts
  clients/assessment_component/src/assessment/pages/components/diagrams/gradeDistributionBarChart/utils/createGradeDistributionDataPoint.ts
  clients/assessment_component/src/assessment/pages/components/diagrams/hooks/useGetParticipantWithAssessment.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/hooks/useGetParticipationsWithAssessment.tsx
  clients/assessment_component/src/assessment/pages/components/diagrams/interfaces/ParticipationWithAssessment.ts
  clients/assessment_component/src/assessment/pages/components/diagrams/scoreDistributionBarChart/utils/createScoreDistributionDataPoint.ts
  clients/assessment_component/src/assessment/pages/components/diagrams/utils/computeQuartile.ts
  clients/assessment_component/src/assessment/pages/components/diagrams/utils/getGridSpanClass.ts
  clients/assessment_component/src/assessment/pages/components/diagrams/utils/groupBy.ts
  clients/assessment_component/src/assessment/pages/utils/gradeConfig.ts
  servers/assessment/assessments/assessmentCompletion/assessmentCompletionDTO/assessmentCompletion.go
  servers/assessment/assessments/assessmentCompletion/service.go
  servers/assessment/assessments/scoreLevel/scoreLevelDTO/scoreLevelWithParticipation.go
  servers/assessment/db/query/scoreLevel.sql
  servers/assessment/db/sqlc/scoreLevel.sql.go
  servers/assessment/utils/numericConversion.go
Labels: schau mi o

#794 `General`: Bump version to 2.5.0
  clients/assessment_component/package.json
  clients/core/package.json
  clients/devops_challenge_component/package.json
  clients/interview_component/package.json
  clients/intro_course_developer_component/package.json
  clients/matching_component/package.json
  clients/package.json
  clients/self_team_allocation_component/package.json
  clients/team_allocation_component/package.json
  clients/template_component/package.json
Labels: schau mi o

#785 `Assessment`: Refactor Deadline Badge to better display once the deadline has passed
  clients/assessment_component/src/assessment/interfaces/assessmentType.ts
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletion/AssessmentCompletion.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletion/components/GradeSuggestion.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentProfile.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/CategoryAssessment.tsx
  clients/assessment_component/src/assessment/pages/AssessmentParticipantsPage/AssessmentParticipantsPage.tsx
  clients/assessment_component/src/assessment/pages/SelfAndPeerEvaluationOverviewPage/SelfAndPeerEvaluationOverviewPage.tsx
  clients/assessment_component/src/assessment/pages/SelfAndPeerEvaluationOverviewPage/components/EvaluationInfoCard.tsx
  clients/assessment_component/src/assessment/pages/SelfAndPeerEvaluationOverviewPage/components/PeerEvaluationStatusCard.tsx
  clients/assessment_component/src/assessment/pages/SelfAndPeerEvaluationOverviewPage/components/SelfEvaluationStatusCard.tsx
  clients/assessment_component/src/assessment/pages/SelfAndPeerEvaluationPage/components/EvaluationCompletionPage/EvaluationCompletionPage.tsx
  clients/assessment_component/src/assessment/pages/SelfAndPeerEvaluationPage/components/EvaluationForm/EvaluationForm.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/SettingsPage.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/CategoryList/CategoryList.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/CoursePhaseConfigSelection/CoursePhaseConfigSelection.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/CoursePhaseConfigSelection/components/AssessmentConfiguration.tsx
  clients/assessment_component/src/assessment/pages/components/CompetencyHeader.tsx
  clients/assessment_component/src/assessment/pages/components/DeadlineBadge.tsx
  clients/assessment_component/src/assessment/pages/components/ScoreLevelSelector.tsx
  clients/assessment_component/src/assessment/pages/components/badges/AssessmentStatusBadge.tsx
  clients/assessment_component/src/assessment/pages/components/badges/DeadlineBadge.tsx
  clients/assessment_component/src/assessment/pages/components/badges/GradeSuggestionBadge.tsx
  clients/assessment_component/src/assessment/pages/components/badges/PeerEvaluationCompletionBadge.tsx
  clients/assessment_component/src/assessment/pages/components/badges/StudentScoreBadge.tsx
  clients/assessment_component/src/assessment/pages/components/badges/TeamBadge.tsx
  clients/assessment_component/src/assessment/pages/components/badges/index.ts
  clients/assessment_component/src/assessment/pages/components/diagrams/AssessmentDiagram.tsx
Labels: schau mi o

#797 [CI] Update Dockerfile to remove redundant copy
  clients/core/Dockerfile
Labels: Component: Core, General

#802 `Documentation`: Create Server Guidelines
  docs/contributor/guide/server.md
Labels: schau mi o

#817 `Core`: Update breadcrumb logic
  clients/core/src/managementConsole/layout/Breadcrumbs/Breadcrumbs.tsx
Labels: schau mi o

#796 `Templating`: UI Improvements (+ fix copy of application deadline)
  clients/core/src/managementConsole/courseConfigurator/components/HelpDialog.tsx
  clients/core/src/managementConsole/courseConfigurator/handlers/useDrop.ts
  clients/core/src/managementConsole/courseOverview/AddingCourse/AddTemplateProperties.tsx
  clients/core/src/managementConsole/courseOverview/AddingCourse/components/CourseCreationChoiceDialog.tsx
  clients/core/src/managementConsole/courseOverview/AddingCourse/components/TemplateSelectionDialog.tsx
  clients/core/src/managementConsole/courseOverview/components/CopyCourseDialog.tsx
  clients/core/src/managementConsole/courseOverview/components/MakeTemplateCourseForm.tsx
  clients/core/src/managementConsole/courseOverview/components/WarningStep.tsx
  clients/core/src/managementConsole/layout/Sidebar/CourseSwitchSidebar/components/AddCourseSidebarItem.tsx
  clients/core/src/managementConsole/shared/components/CourseCards.tsx
  clients/core/src/network/hooks/useCopyCourse.ts
  clients/core/src/network/hooks/useTemplateForm.ts
  servers/core/course/copy/check_course_copyable.go
  servers/core/course/copy/copy_phases.go
Labels: schau mi o
