Repository ls1intum/prompt2, pull requests merged in 2025-04, with the labels that each got.

#345 `DevOpsChallenge`: Remove duplicate mutation call
  clients/devops_challenge_component/src/devops_challenge/components/Assessment.tsx
Labels: Component:: GitHubCodingChallenge

#340 `Assessment`: Setup assessment Server and Assessment DB Structure
  .gitignore
  docker-compose.yml
  servers/assessment/db/migration/0001_schema.up.sql
  servers/assessment/db/query/assessment.sql
  servers/assessment/db/query/category.sql
  servers/assessment/db/query/competency.sql
  servers/assessment/db/sqlc/assessment.sql.go
  servers/assessment/db/sqlc/category.sql.go
  servers/assessment/db/sqlc/competency.sql.go
  servers/assessment/db/sqlc/db.go
  servers/assessment/db/sqlc/models.go
  servers/assessment/go.mod
  servers/assessment/go.sum
  servers/assessment/main.go
  servers/assessment/sqlc.yaml
  servers/assessment/utils/getCoreUrl.go
Labels: Component:: Assessment

#369 `Intro Course`: Add TUM CIT Rechnerhallen Seat Layout
  clients/intro_course_developer_component/src/introCourse/pages/SeatAssignment/utils/rechnerHalle.ts
Labels: schau mi o

#344 `Assessment`: Setup Server Endpoints
  servers/assessment/assessments/assessmentDTO/assessment.go
  servers/assessment/assessments/assessmentDTO/createOrUpdateAssessmentRequest.go
  servers/assessment/assessments/main.go
  servers/assessment/assessments/router.go
  servers/assessment/assessments/service.go
  servers/assessment/categories/categoryDTO/category.go
  servers/assessment/categories/categoryDTO/categoryWithCompetency.go
  servers/assessment/categories/categoryDTO/createCategoryRequest.go
  servers/assessment/categories/categoryDTO/updateCategoryRequest.go
  servers/assessment/categories/main.go
  servers/assessment/categories/router.go
  servers/assessment/categories/service.go
  servers/assessment/competencies/competencyDTO/competency.go
  servers/assessment/competencies/competencyDTO/createCompetencyRequest.go
  servers/assessment/competencies/competencyDTO/updateCompetencyRequest.go
  servers/assessment/competencies/main.go
  servers/assessment/competencies/router.go
  servers/assessment/competencies/service.go
  servers/assessment/db/query/assessment.sql
  servers/assessment/db/sqlc/assessment.sql.go
  servers/assessment/docs/openapi.yaml
  servers/assessment/main.go
Labels: Component:: Assessment, schau mi o

#305 `Intro Course` Gitlab Automatic Repo Creation
  .github/workflows/deploy-docker.yml
  clients/intro_course_developer_component/src/introCourse/interfaces/GitlabCourseInfrastructureRequest.ts
  clients/intro_course_developer_component/src/introCourse/interfaces/GitlabRepoRequest.ts
  clients/intro_course_developer_component/src/introCourse/interfaces/GitlabStatus.ts
  clients/intro_course_developer_component/src/introCourse/interfaces/Tutor.ts
  clients/intro_course_developer_component/src/introCourse/interfaces/UpdateTutor.ts
  clients/intro_course_developer_component/src/introCourse/network/mutations/createGitlabRepo.ts
  clients/intro_course_developer_component/src/introCourse/network/mutations/createIntroCourseGitlabInfrastructure.ts
  clients/intro_course_developer_component/src/introCourse/network/mutations/updateGitlabStatus.ts
  clients/intro_course_developer_component/src/introCourse/network/mutations/updateTutor.ts
  clients/intro_course_developer_component/src/introCourse/network/queries/getGitlabStatuses.ts
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/DeveloperProfilesLecturerPage.tsx
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/components/CreateGitlabReposDialog.tsx
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/components/FilterMenu.tsx
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/components/ProfileDetailsDialog.tsx
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/hooks/useGetFilteredParticipations.tsx
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/hooks/useGetParticipationsWithProfiles.tsx
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/hooks/useGetSortedParticipations.tsx
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/interfaces/devProfileFilter.ts
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/interfaces/pariticipationWithDevProfiles.ts
  clients/intro_course_developer_component/src/introCourse/pages/SeatAssignment/SeatAssignmentPage.tsx
  clients/intro_course_developer_component/src/introCourse/pages/SeatAssignment/hooks/useGetParticipationWithDevProfile.tsx
  clients/intro_course_developer_component/src/introCourse/pages/TutorImport/components/TutorTable.tsx
  docker-compose.prod.yml
  servers/intro_course/db/migration/0004_add_tutor_gitlab.up.sql
  servers/intro_course/db/query/gitlab.sql
  servers/intro_course/db/query/seat.sql
  servers/intro_course/db/query/tutor.sql
  servers/intro_course/db/sqlc/gitlab.sql.go
  servers/intro_course/db/sqlc/models.go
  servers/intro_course/db/sqlc/seat.sql.go
  servers/intro_course/db/sqlc/tutor.sql.go
  servers/intro_course/go.mod
  servers/intro_course/go.sum
  servers/intro_course/infrastructureSetup/data/gitignore.go
  servers/intro_course/infrastructureSetup/data/readme.go
  servers/intro_course/infrastructureSetup/data/swiftlint.go
  servers/intro_course/infrastructureSetup/gitlab.go
  servers/intro_course/infrastructureSetup/infrastructureDTO/create_course_infrastructure.go
  servers/intro_course/infrastructureSetup/infrastructureDTO/create_student_repo.go
  servers/intro_course/infrastructureSetup/infrastructureDTO/get_gitlab_status.go
  servers/intro_course/infrastructureSetup/main.go
  servers/intro_course/infrastructureSetup/router.go
  servers/intro_course/infrastructureSetup/service.go
  servers/intro_course/main.go
  servers/intro_course/tutor/router.go
  servers/intro_course/tutor/service.go
  servers/intro_course/tutor/tutorDTO/tutor.go
  servers/intro_course/tutor/tutorDTO/update_tutor.go
Labels: schau mi o

#379 `Intro Course`: Fixing Group Assignment
  servers/intro_course/infrastructureSetup/gitlab.go
  servers/intro_course/infrastructureSetup/service.go
Labels: schau mi o

#393 `Team Allocation`: Fixing Type and Deployment
  .github/workflows/deploy-docker.yml
  docker-compose.prod.yml
  servers/core/coursePhaseType/initializeTypes.go
  servers/core/coursePhaseType/main.go
  servers/core/db/query/course_phase_type.sql
  servers/core/db/sqlc/course_phase_type.sql.go
Labels: schau mi o

#394 `Intro Course`: Adding Endpoint for Exporting the Devices
  servers/intro_course/db/query/devices.sql
  servers/intro_course/db/sqlc/devices.sql.go
  servers/intro_course/developerProfile/developerProfileDTO/deviceWithParticipationID.go
  servers/intro_course/developerProfile/router.go
  servers/intro_course/developerProfile/service.go
Labels: schau mi o

#399 `Assessment`: update access rights for endpoints to give tutors access
  servers/assessment/assessments/router.go
  servers/assessment/categories/router.go
  servers/assessment/competencies/router.go
Labels: Component:: Assessment, schau mi o

#397 `Team Allocation`: Migrating the Skill Level
  clients/team_allocation_component/src/team_allocation/interfaces/skillResponse.ts
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/StudentSurveyPage.tsx
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/components/SkillRanking.tsx
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/components/SurveyForm.tsx
  servers/team_allocation/db/migration/0002_enum.up.sql
  servers/team_allocation/db/query/survey.sql
  servers/team_allocation/db/sqlc/models.go
  servers/team_allocation/db/sqlc/survey.sql.go
  servers/team_allocation/main.go
  servers/team_allocation/survey/service.go
  servers/team_allocation/survey/surveyDTO/studentSkillRepsonse.go
  servers/team_allocation/survey/validation.go
Labels: schau mi o

#396 `Team Allocation`: Tease Endpoint for Available Course Phases
  servers/team_allocation/coreRequests/coreRequestDTO/course.go
  servers/team_allocation/coreRequests/getCourses.go
  servers/team_allocation/db/query/tease.sql
  servers/team_allocation/db/sqlc/getTimeoutContext.go
  servers/team_allocation/db/sqlc/tease.sql.go
  servers/team_allocation/go.mod
  servers/team_allocation/go.sum
  servers/team_allocation/main.go
  servers/team_allocation/tease/main.go
  servers/team_allocation/tease/router.go
  servers/team_allocation/tease/service.go
  servers/team_allocation/tease/teaseDTO/teasePhase.go
Labels: schau mi o

#403 `Assessment`: Prompt SDK Version Bump
  servers/assessment/go.mod
  servers/assessment/go.sum
Labels: Component:: Assessment

#390 `Intro Course`: UI Overflow Improvements
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/DeveloperProfilesLecturerPage.tsx
  clients/intro_course_developer_component/src/introCourse/pages/SeatAssignment/components/SeatUploader/SeatPlanDialog.tsx
  clients/intro_course_developer_component/src/introCourse/pages/TutorImport/components/StudentSelection.tsx
Labels: schau mi o

#408 `General`: Version Bump to v2.2.13
  clients/assessment_component/package.json
  clients/core/package.json
  clients/devops_challenge_component/package.json
  clients/interview_component/package.json
  clients/intro_course_developer_component/package.json
  clients/intro_course_tutor_component/package.json
  clients/matching_component/package.json
  clients/package.json
  clients/team_allocation_component/package.json
  clients/template_component/package.json
  servers/assessment/assessments/service.go
Labels: schau mi o

#405 `Team Allocation`: Endpoints for skills and teams for Tease Integration
  servers/team_allocation/tease/router.go
  servers/team_allocation/tease/service.go
  servers/team_allocation/tease/teaseDTO/teaseSkill.go
  servers/team_allocation/tease/teaseDTO/teaseTeam.go
Labels: schau mi o

#411 `Assessment`: Mark Submission as Final
  clients/assessment_component/readme
  clients/assessment_component/src/assessment/interfaces/assessment.ts
  clients/assessment_component/src/assessment/interfaces/studentAssessment.ts
  clients/assessment_component/src/assessment/network/mutations/createAssessmentCompletion.ts
  clients/assessment_component/src/assessment/network/mutations/deleteAssessmentCompletion.ts
  clients/assessment_component/src/assessment/network/queries/getAllStudentAssessmentsInPhase.ts
  clients/assessment_component/src/assessment/network/queries/getRemainingAssessmentsForStudent.ts
  clients/assessment_component/src/assessment/network/queries/getRemainingAssessmentsForStudentPerCategory.ts
  clients/assessment_component/src/assessment/network/queries/getStudentAssessment.ts
  clients/assessment_component/src/assessment/pages/AssessmentPage/AssessmentPage.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletionDialog.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentForm.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentProfile.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentStatusBadge.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/CategoryAssessment.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useCreateAssessmentCompletion.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useDeleteAssessmentCompletion.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useGetAllStudentAssessmentsInPhase.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useGetRemainingAssessmentsForStudent.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useGetStudentAssessment.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useUpdateAssessment.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/hooks/useCreateCategory.ts
  clients/assessment_component/src/assessment/pages/SettingsPage/hooks/useCreateCompetency.ts
  clients/assessment_component/src/assessment/pages/SettingsPage/hooks/useDeleteCategory.ts
  clients/assessment_component/src/assessment/pages/SettingsPage/hooks/useDeleteCompetency.ts
  clients/assessment_component/src/assessment/pages/SettingsPage/hooks/useUpdateCategory.ts
  clients/assessment_component/src/assessment/pages/SettingsPage/hooks/useUpdateCompetency.ts
  servers/assessment/assessments/assessmentCompletion/assessmentCompletionDTO/assessmentCompletion.go
  servers/assessment/assessments/assessmentCompletion/main.go
  servers/assessment/assessments/assessmentCompletion/router.go
  servers/assessment/assessments/assessmentCompletion/service.go
  servers/assessment/assessments/assessmentDTO/studentAssessment.go
  servers/assessment/assessments/remainingAssessments/main.go
  servers/assessment/assessments/remainingAssessments/remainingAssessmentsDTO/remainingAssessments.go
  servers/assessment/assessments/remainingAssessments/router.go
  servers/assessment/assessments/remainingAssessments/service.go
  servers/assessment/assessments/router.go
  servers/assessment/assessments/service.go
  servers/assessment/db/migration/0003_final_assessment.up.sql
  servers/assessment/db/query/assessment_completion.sql
  servers/assessment/db/sqlc/assessment_completion.sql.go
  servers/assessment/db/sqlc/models.go
  servers/assessment/docs/openapi.yaml
  servers/assessment/main.go
  servers/assessment/validation/assessmentCompletion.go
Labels: Component:: Assessment, schau mi o

#406 `Team Allocation`: DB Migration and Allocations Endpoints
  servers/team_allocation/db/migration/0003_allocations.up.sql
  servers/team_allocation/db/query/allocation.sql
  servers/team_allocation/db/sqlc/allocation.sql.go
  servers/team_allocation/db/sqlc/db.go
  servers/team_allocation/db/sqlc/models.go
  servers/team_allocation/db/sqlc/skill.sql.go
  servers/team_allocation/db/sqlc/survey.sql.go
  servers/team_allocation/db/sqlc/team.sql.go
  servers/team_allocation/db/sqlc/tease.sql.go
  servers/team_allocation/tease/router.go
  servers/team_allocation/tease/service.go
  servers/team_allocation/tease/teaseDTO/allocation.go
Labels: schau mi o

#419 `General`: Remove Output File Option from ESLint Command in Lint-Clients Workflow
  .github/workflows/lint-clients.yml
  clients/assessment_component/src/assessment/pages/SettingsPage/components/EditCategoryDialog.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/EditCompetencyDialog.tsx
Labels: GitHub Action, schau mi o

#422 `General`: Remove Annotate Lint Clients Job from Lint and Test Prod Workflow
  .github/workflows/lint-test-prod.yml
Labels: GitHub Action, schau mi o

#426 `Team Allocation`: Overview Page
  clients/shared_library/tailwind.config.js
  clients/team_allocation_component/routes/index.tsx
  clients/team_allocation_component/sidebar/index.tsx
  clients/team_allocation_component/src/team_allocation/interfaces/allocation.ts
  clients/team_allocation_component/src/team_allocation/network/queries/getTeamAllocations.ts
  clients/team_allocation_component/src/team_allocation/pages/TeamAllocation/TeamAllocationPage.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeamAllocation/components/AllocationSummaryCard.tsx
Labels: schau mi o

#427 `Team Allocation`: Add Validation to the Student Survey
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/components/SkillRanking.tsx
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/components/SurveyForm.tsx
  servers/team_allocation/survey/router.go
  servers/team_allocation/survey/validation.go
Labels: schau mi o

#420 `General`: Resolution URL Loading
  servers/core/coursePhase/coursePhaseDTO/get_course_phase_prev_data.go
  servers/core/coursePhase/coursePhaseDTO/prev_course_phase_resolution.go
  servers/core/coursePhase/coursePhaseParticipation/coursePhaseParticipationDTO/get_participations_with_resolution.go
  servers/core/coursePhase/coursePhaseParticipation/coursePhaseParticipationDTO/resolution.go
  servers/core/coursePhase/coursePhaseParticipation/router_test.go
  servers/core/coursePhase/coursePhaseParticipation/service.go
  servers/core/coursePhase/coursePhaseParticipation/service_test.go
  servers/core/coursePhase/resolution/main.go
  servers/core/coursePhase/resolution/resolutionDTO/resolution.go
  servers/core/coursePhase/resolution/service.go
  servers/core/coursePhase/router_test.go
  servers/core/coursePhase/service.go
  servers/core/coursePhase/service_test.go
  servers/core/coursePhaseType/initializeTypes.go
  servers/core/coursePhaseType/main.go
  servers/core/coursePhaseType/service.go
  servers/core/db/sqlc/application.sql.go
  servers/core/db/sqlc/course.sql.go
  servers/core/db/sqlc/course_graph.sql.go
  servers/core/db/sqlc/course_participation.sql.go
  servers/core/db/sqlc/course_phase.sql.go
  servers/core/db/sqlc/course_phase_participation.sql.go
  servers/core/db/sqlc/course_phase_type.sql.go
  servers/core/db/sqlc/db.go
  servers/core/db/sqlc/mailing.sql.go
  servers/core/db/sqlc/meta_data_graph.sql.go
  servers/core/db/sqlc/models.go
  servers/core/db/sqlc/permission_strings.sql.go
  servers/core/db/sqlc/resolution.sql.go
  servers/core/db/sqlc/students.sql.go
  servers/core/main.go
Labels: schau mi o

#435 `Team Allocation`: Disabling Survey After Deadline
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/components/SkillRanking.tsx
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/components/SurveyForm.tsx
  clients/team_allocation_component/src/team_allocation/pages/StudentSurvey/components/TeamRanking.tsx
Labels: schau mi o

#434 `Core`: Improving Application Auth
  servers/core/applicationAdministration/router.go
  servers/core/applicationAdministration/service.go
  servers/core/applicationAdministration/service_test.go
  servers/core/db/query/students.sql
  servers/core/db/sqlc/students.sql.go
  servers/core/student/service.go
Labels: schau mi o

#433 `Assessment`: Fix Assessment Page Design and Mark Submission as Final Flow
  clients/assessment_component/src/assessment/interfaces/assessment.ts
  clients/assessment_component/src/assessment/interfaces/scoreLevelWithParticipation.ts
  clients/assessment_component/src/assessment/network/queries/getAllScoreLevels.ts
  clients/assessment_component/src/assessment/pages/AssessmentOverviewPage/AssessmentOverviewPage.tsx
  clients/assessment_component/src/assessment/pages/AssessmentOverviewPage/hooks/useGetAllScoreLevels.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentForm.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentProfile.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/StudentScoreBadge.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useCreateAssessmentCompletion.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/hooks/useDeleteAssessmentCompletion.tsx
  clients/assessment_component/src/assessment/pages/components/StudentScoreBadge.tsx
  clients/shared_library/components/pages/CoursePhaseParticpationsTable/CoursePhaseParticipationsTablePage.tsx
  clients/shared_library/tailwind.config.js
  clients/team_allocation_component/src/team_allocation/pages/TeamAllocation/components/AllocationSummaryCard.tsx
  servers/assessment/assessments/assessmentCompletion/assessmentCompletionDTO/assessmentCompletion.go
  servers/assessment/assessments/assessmentCompletion/service.go
  servers/assessment/assessments/scoreLevel/service.go
  servers/assessment/assessments/service.go
  servers/assessment/db/migration/0005_alter_timezones.up.sql
  servers/assessment/db/migration/0006_completed_score_levels.up.sql
  servers/assessment/db/query/assessment.sql
  servers/assessment/db/query/scoreLevel.sql
  servers/assessment/db/sqlc/assessment.sql.go
  servers/assessment/db/sqlc/assessment_completion.sql.go
  servers/assessment/db/sqlc/category.sql.go
  servers/assessment/db/sqlc/competency.sql.go
  servers/assessment/db/sqlc/db.go
  servers/assessment/db/sqlc/models.go
  servers/assessment/db/sqlc/scoreLevel.sql.go
Labels: Component:: Assessment, schau mi o

#413 `Team Allocation`: Tease Configuration Page
  clients/team_allocation_component/routes/index.tsx
  clients/team_allocation_component/sidebar/index.tsx
  clients/team_allocation_component/src/team_allocation/interfaces/studentCheck.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/allocation.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/comment.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/courseIteration.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/device.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/gender.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/language.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/languageProficiency.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/project.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/projectPreference.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/skill.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/skillProficiency.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/student.ts
  clients/team_allocation_component/src/team_allocation/interfaces/tease/studentSkill.ts
  clients/team_allocation_component/src/team_allocation/interfaces/validationResult.ts
  clients/team_allocation_component/src/team_allocation/network/queries/getAllTeaseStudents.ts
  clients/team_allocation_component/src/team_allocation/pages/TeamAllocation/components/AllocationSummaryCard.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeaseConfig/TeaseConfigPage.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeaseConfig/components/CheckItem.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeaseConfig/components/ChecksConfig.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeaseConfig/components/DataCompletionSummary.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeaseConfig/components/StudentDataCheck.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeaseConfig/components/StudentDetailDialog.tsx
  clients/team_allocation_component/src/team_allocation/pages/TeaseConfig/components/SurveySubmissionOverview.tsx
Labels: schau mi o

#447 `Core`: Re-Add IntroCourseDeveloper Initialization
  servers/core/coursePhaseType/initializeTypes.go
  servers/core/coursePhaseType/main.go
Labels: schau mi o

#444 `Assessment`: Fix weight input handling to ensure numeric values are correctly processed
  clients/assessment_component/src/assessment/pages/SettingsPage/components/EditCompetencyDialog.tsx
Labels: Component:: Assessment, schau mi o

#460 `Team Allocation`: Adding Participants Table with Download
  clients/intro_course_developer_component/src/introCourse/pages/DeveloperProfilesLecturer/hooks/useDownloadDeveloperProfiles.tsx
  clients/team_allocation_component/routes/index.tsx
  clients/team_allocation_component/sidebar/index.tsx
  clients/team_allocation_component/src/team_allocation/pages/Participants/ParticipantsPage.tsx
Labels: schau mi o

#463 `Core`: Fixing Tests
  servers/core/applicationAdministration/service_test.go
  servers/core/database_dumps/application_administration.sql
Labels: schau mi o

#464 `Self Team Allocation`: Fixing Overflow
  clients/self_team_allocation_component/src/self_team_allocation/pages/TeamAllocation/components/TeamCard.tsx
  clients/self_team_allocation_component/src/self_team_allocation/pages/TeamAllocation/components/TeamSelection.tsx
Labels: schau mi o

#472 `Assessment`: Changing Import to prompt lib
  clients/assessment_component/src/assessment/pages/AssessmentDataShell.tsx
  clients/assessment_component/src/assessment/pages/AssessmentOverviewPage/AssessmentOverviewPage.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/AssessmentPage.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentCompletionDialog.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentForm.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentProfile.tsx
  clients/assessment_component/src/assessment/pages/AssessmentPage/components/AssessmentStatusBadge.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/SettingsPage.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/CategoryList.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/CompetencyItem.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/CreateCategoryForm.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/CreateCompetencyForm.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/DeleteConfirmDialog.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/EditCategoryDialog.tsx
  clients/assessment_component/src/assessment/pages/SettingsPage/components/EditCompetencyDialog.tsx
  clients/assessment_component/src/assessment/pages/components/StudentScoreBadge.tsx
  clients/assessment_component/tailwind.config.js
  clients/assessment_component/webpack.config.ts
Labels: schau mi o

#470 `Interview`: Changing Import To UI-Lib
  clients/interview_component/src/interview/components/InterviewCard.tsx
  clients/interview_component/src/interview/components/InterviewTimesDialog.tsx
  clients/interview_component/src/interview/components/SortDropdownMenu.tsx
  clients/interview_component/src/interview/components/StudentCard.tsx
  clients/interview_component/src/interview/pages/InterviewDataShell.tsx
  clients/interview_component/src/interview/pages/Mailing/MailingPage.tsx
  clients/interview_component/src/interview/pages/Overview/OverviewPage.tsx
  clients/interview_component/src/interview/pages/ProfileDetail/ProfileDetailPage.tsx
  clients/interview_component/src/interview/pages/QuestionConfiguration/QuestionConfiguration.tsx
Labels: schau mi o

#471 `DevOps Challenge`: Changing Import To UI-Lib
  clients/devops_challenge_component/src/devops_challenge/DevOpsChallengeDataShell.tsx
  clients/devops_challenge_component/src/devops_challenge/components/Assessment.tsx
  clients/devops_challenge_component/src/devops_challenge/components/GithubUsernameInput.tsx
  clients/devops_challenge_component/src/devops_challenge/components/PassCountIndicator.tsx
  clients/devops_challenge_component/src/devops_challenge/components/RepositoryInformation.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/Mailing/MailingPage.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/ResultsOverviewPage.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/columns.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/components/FilterMenu.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/components/GroupActionsMenu.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/components/SelectStudentsDialog.tsx
  clients/devops_challenge_component/src/devops_challenge/pages/ResultsOverviewPage/utils/getChallengeStatusBadge.tsx
  clients/devops_challenge_component/src/index.js
  clients/devops_challenge_component/tailwind.config.js
  clients/devops_challenge_component/webpack.config.ts
Labels: schau mi o

#467 `General`: Change About Page
  clients/core/src/publicPages/legalPages/components/ContributorMapping.tsx
Labels: schau mi o
